/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_health_thermometer             19
#define gattdb_temperature_measurement_0      21
#define gattdb_temperature_measurement_1      24
#define gattdb_temperature_measurement_2      27
#define gattdb_temperature_measurement_3      30
#define gattdb_temperature_measurement_4      33
#define gattdb_temperature_measurement_5      36
#define gattdb_temperature_measurement_6      39
#define gattdb_temperature_measurement_7      42
#define gattdb_ota                            44
#define gattdb_ota_control                    46


#endif // __GATT_DB_H
